muneris/config/routes.rb
Muneris::Application.routes.draw do


  authenticated :user do
    root :to => "muneris#dashboard" , :as => "authenticated_root"
    # Rails 4 users must specify the 'as' option to give it a unique name
    # root :to => "main#dashboard", :as => "authenticated_root"
  end

  root :to => "welcome#index"

  resources :bills

  resources :network, :controller => 'friendships', :except => [:show, :edit] do
    get "requests", :on => :collection
    get "invites", :on => :collection
  end
  
  # get "/user/:id/feed", to: 'user#feed', as: :feed
  # get "/user/:id/notifications", to: 'user#notifications', as: :notifications
  # get "/user/:id/network", to: 'user#network', as: :usernetwork
  get "/dashboard", to: 'muneris#dashboard', as: :dashboard
  get "/profile(/:user_id)", to: 'muneris#profile', as: :profile
  get "/statistics", to: 'muneris#statistics', as: :statistics
  get "/map", to: 'muneris#map', as: :map
  get "/map/info/:user_map_id", to: 'muneris#map'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  delete 'profile/:id' => 'user#destroy', :as => :admin_destroy_user  

end

muneris/app/views/layouts/partials/_activity.html.erb
<div class="w-col w-col-5">
  <h1>Activity</h1>
 	
 	<div class="w-row">
<!-- 		<div id="radio_buttons">
			<%#= radio_button_tag(:option, "consumption", :id => 'yesCheck', :onclick => "javascript:yesnoCheck();") %>
			<%#= label_tag(:option_consumption, "I want to see my consumption") %>
			<%#= radio_button_tag(:option, "payment", :id => 'noCheck', :onclick => "javascript:yesnoCheck();") %>
			<%#= label_tag(:option_payment, "I want to see my payment") %>
		</div> -->
		<div id="radio_buttons">
		    <form class="type flash">
		        <input type="radio" name="type" checked="checked" value="consumption">Show consumption stats</input>
		        <input type="radio" name="type" value="payment">Show payment stats</input>
		    </form>
		</div>   
	 	<div class="w-col w-col-6">
		 	<h3><strong>Records</strong></h3>
		 	<%= render partial: 'layouts/partials/grids' %>
	 	</div>
	 	<div class="w-col w-col-6">
		 	<h3><strong>Statistics</strong></h3>
		 	<div id="consumption-table">
		 		<%= render partial: 'layouts/partials/charts' %>
		 	</div>
		 	<div id="payment-table">
		 		<%= render partial: 'layouts/partials/charts2' %>
		 	</div>
	 	</div>
	</div>
</div>

<script>
    $( document ).ready(function() {

    	$('#consumption-table').show();
    	$('#payment-table').hide();

		$("#radio_buttons input[name='type']").click(function(){
		    if($('input:radio[name=type]:checked').val() == "consumption"){
		    	$('#consumption-table').show();
		    	$('#payment-table').hide();
		        //$('#select-table > .roomNumber').attr('enabled',false);
		    }
		    if($('input:radio[name=type]:checked').val() == "payment"){
		    	$('#consumption-table').hide();
		    	$('#payment-table').show();
		        //$('#select-table > .roomNumber').attr('enabled',false);
		    }
		});
    });


</script>

muneris/app/views/layouts/partials/_blank.html.erb
<div class="w-col">
<p>
No records found.
<br>
<%	case section
		when 'bill' then %>	 Go <%= link_to 'here', new_bill_path %> to add a bill.
	<% 	when 'net' then %>   Go <%= link_to 'here', new_network_path %> to add some users.
<% end %>
</p>
<br>

</div>

muneris/app/views/layouts/partials/_charts.html.erb
<div class="w-box">
<p><strong>Energy vs. time</strong></p>
<%=	if !@ebills.empty? then
		high_stock('echart', @echart)
	else
		render partial: 'layouts/partials/blank', locals: { section: 'bill' } 
	end %>
</div>
<div class="w-box">
<p><strong>Water vs. time</strong></p>
<%=	if !@wbills.empty? then
		high_stock('wchart', @wchart)
	else
		render partial: 'layouts/partials/blank', locals: { section: 'bill' } 
	end %>
</div>
<div class="w-box">
<p><strong>Gas vs. time</strong></p>
<%=	if !@gbills.empty? then
		high_stock('gchart', @gchart)
	else
		render partial: 'layouts/partials/blank', locals: { section: 'bill' } 
	end %>
</div>

muneris/app/views/layouts/partials/_charts2.html.erb
<div class="w-box">
<p><strong>Energy vs. time</strong></p>
<%=	if !@ebills.empty? then
		high_stock('evchart', @evchart)
	else
		render partial: 'layouts/partials/blank', locals: { section: 'bill' } 
	end %>
</div>
<div class="w-box">
<p><strong>Water vs. time</strong></p>
<%=	if !@wbills.empty? then
		high_stock('wvchart', @wvchart)
	else
		render partial: 'layouts/partials/blank', locals: { section: 'bill' } 
	end %>
</div>
<div class="w-box">
<p><strong>Gas vs. time</strong></p>
<%=	if !@gbills.empty? then
		high_stock('gvchart', @gvchart)
	else
		render partial: 'layouts/partials/blank', locals: { section: 'bill' } 
	end %>
</div>

muneris/app/views/layouts/partials/_footer.html.erb
</body>
<footer>
  <div class="section footer">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6 left-footer-col">
          <div class="footer-text">© Muneris.</div>
        </div>
        <div class="w-col w-col-6 footer-nav-bar">
        <a class="footer-link" href="mailto:jscamargo@uninorte.edu.co">Contacts us</a>
        <a class="footer-link" href="http://www.uninorte.edu.co">Universidad del Norte</a>

        </div>
      </div>
    </div>
  </div>
</footer>

muneris/app/views/layouts/partials/_grids.html.erb
<div class="w-box">
<p><strong>Energy bills</strong></p>
<%= grid(@ebills_grid, allow_showing_all_records: false, show_filters: :no) do |g|

  g.blank_slate  partial: 'layouts/partials/blank', locals: { section: 'bill' } 

  g.column name: 'Consumption', attribute: 'consumption' do |bill|
    bill.consumption.to_s + " kWh"
  end

  g.column  name: 'Payment', attribute: 'value' do |bill|
    number_to_currency(bill.value, :precision => 0)
  end

  g.column name: 'Date', attribute: 'date' do |bill|
    bill.date.strftime "%b %Y"
  end

end %>
</div>
<div class="w-box">
<p><strong>Water bills</strong></p>
<%= grid(@wbills_grid, allow_showing_all_records: false, show_filters: :no) do |g|

  g.blank_slate  partial: 'layouts/partials/blank', locals: { section: 'bill' } 

  g.column name: 'Consumption', attribute: 'consumption' do |bill|
    bill.consumption.to_s + " m3"
  end

  g.column  name: 'Payment', attribute: 'value' do |bill|
    number_to_currency(bill.value, :precision => 0)
  end

  g.column name: 'Date', attribute: 'date' do |bill|
    bill.date.strftime "%b %Y"
  end

end %>
</div>
<div class="w-box">
<p><strong>Gas bills</strong></p>

<%= grid(@gbills_grid, allow_showing_all_records: false, show_filters: :no) do |g|

  g.blank_slate  partial: 'layouts/partials/blank', locals: { section: 'bill' } 

  g.column name: 'Consumption', attribute: 'consumption' do |bill|
    bill.consumption.to_s + " m3"
  end

  g.column  name: 'Payment', attribute: 'value' do |bill|
    number_to_currency(bill.value, :precision => 0)
  end

  g.column name: 'Date', attribute: 'date' do |bill|
    bill.date.strftime "%b %Y"
  end

end %>
</div>

muneris/app/views/layouts/partials/_header.html.erb
<!DOCTYPE html>

<html data-wf-site="52e85101141f8e087d000001">
<head>
  <meta charset="utf-8">
  <title>Muneris</title>
  <meta name="description" content="Muneris is a social network that helps households and local businesses administrate and share their consumption bills.">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
  

  <script>
    WebFont.load({
      google: {
        families: ["Open Sans:300,400,600,700,800","Duru Sans:regular:latin-ext,latin","Carrois Gothic:regular","Dosis:200,regular"]
      }
    });
  </script>

  <script>
    if (/mobile/i.test(navigator.userAgent)) document.documentElement.className += ' w-mobile';
  </script>

  <%= favicon_link_tag 'favicon.ico' %>
  <link rel="apple-touch-icon" href="assets/images/thumbnail-icon.png">
  
</head>

<body>
    
    <%= render partial: 'layouts/partials/navbar' %>

    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: [name, ' flash'].join %>
    <% end -%>

muneris/app/views/layouts/partials/_infowindow.html.erb
  <%= image_tag user.avatar.url, class: "activity-image" %>
  <h4><%= link_to user.familyname, profile_path(user.id) %></h4>
  <% if !user.bills.empty? then %>
    <br>Latest consumption: <strong><%= user.bills.order("created_at").last.consumption %>
                  <%= case user.bills.order("created_at").last.service
                      when 1
                        "kWh"
                      else
                        "m3"
                      end %></strong>
    <br>Latest payment:<strong><%= number_to_currency(user.bills.order("created_at").last.value, :precision => 0) %></strong>
  <% end %>      
    <br>Network: <strong><%= user.friends.count(:id) %> users</strong>

  

muneris/app/views/layouts/partials/_navbar.html.erb
<div class="section header">
  <div class="w-container">
    <div class="w-row">
      <div class="w-col w-col-4 company-column">
        <% if user_signed_in? %>
        <%= link_to (image_tag 'logomuneris.png', class: "logo") , dashboard_path %>       
        <% else %>
        <%= link_to (image_tag 'logomuneris.png', class: "logo") , root_path %>
        <% end %>        
      </div>

      <div class="w-col w-col-8 nav-bar">

        <% if user_signed_in? and !@user.admin? %>
          <div id="notifications" class="w-col w-col-3 notifications" style="display: none;">
            <%= render partial: 'user/notifications' %>
          </div>
          <%= link_to 'Dashboard',dashboard_path, class: "clickable nav-link" %>                        
          <%= link_to 'Profile',profile_path, class: "clickable nav-link" %>
          <%= link_to 'Bills', bills_path, class: "clickable nav-link" %>
          <%= link_to 'Network',network_index_path, class: "clickable nav-link" %>
          <%= link_to 'Map', map_path, class: "nav-link", 'data-no-turbolink' => true %>
          <%= link_to_modal (image_tag 'notification-icon-alt.png') , "#notifications" , class: "clickable nav-link" %> 
          <%= current_user.familyname %>
          <%= link_to "Sign out", destroy_user_session_path, :class=> "clickable nav-link log-in", :method => :delete %>

        <% elsif user_signed_in? and @user.admin? %> 
          <%= link_to 'Dashboard',dashboard_path, class: "nav-link" %>
          <%= link_to 'Users',network_index_path, class: "nav-link" %>
          <%= link_to 'Map', map_path, class: "nav-link", 'data-no-turbolink' => true %>
          <%=  'Admin' || current_user.familyname %>
          <%= link_to "Sign out", destroy_user_session_path, :class=> "clickable nav-link log-in", :method => :delete %>

        <% else %>
          <%= link_to "Sign in", new_user_session_path, :class=> "clickable nav-link log-in" %>
          <%= link_to "Sign up", new_user_registration_path, :class=> "clickable nav-link sign-up" %> 
          <%#= link_to "Enter with Facebook", user_omniauth_authorize_path(:facebook), :class=> "nav-link sign-up" %>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

muneris/app/views/layouts/partials/_people.html.erb
<div class="w-container">
  <div class="w-row">

    <div class="user-grid-item">
      <% for friendship in @friends %>
      <div class="w-col">
        <div class="usercircleprofile">
          <%= link_to image_tag(friendship.avatar.url, class: "usercircleprofile"), profile_path(friendship.id) %>
        </div>
        <div class="user-grid-label">      
          <%= h link_to friendship.familyname, profile_path(friendship.id) %>
        </div>
      </div>
      <% end %>
    </div>

  </div>
</div>

muneris/app/views/layouts/partials/_sidebar.html.erb
<div class="w-col w-col-3">

  <div>
    <div class="profle-banner profile-picture">
      <%= image_tag @user.avatar.url(:profile) %>  
    </div>
    <h4><%= @user.familyname %></h4>
    <div>

        <% if !@user.bills.empty? then %>
          <p>Latest consumption:
            <br><strong><%= @user.bills.order("created_at").last.consumption %>
                        <%= case @user.bills.order("created_at").last.service
                            when 1
                              "kWh"
                            else
                              "m3"
                            end %></strong></p>
          <p>Latest payment:
            <br><strong><%= number_to_currency(@user.bills.order("created_at").last.value, :precision => 0) %> </strong></p>
        <% end %>      
          <p>Network: <strong><%= @user.friends.count(:id) %> Users </strong></p>
          <p><strong><%= @user.name %></strong></p>
      
    <strong><p><%= @user.address %></strong></p>
    <strong><p><%= @user.tariff %></strong></p>
    <strong><p><%= @user.locale %></strong></p>
    </div>
  </div>

  <% if @is_current_user then %>
    <ul class="w-list-unstyled">
      <li>
        <div class="w-row">
          <div class="w-col w-col-2">
            <%= link_to image_tag("add.png"), new_bill_path %>
          </div>
          <div class="w-col w-col-10">
            <%= link_to 'Add new bill',new_bill_path, class: "profile-sections" %>
          </div>
        </div>
      </li>
      <li>
        <div class="w-row">

          <div class="w-col w-col-2">
            <%= link_to image_tag("add.png"), new_network_path %>
          </div>
          <div class="w-col w-col-10">
            <%= link_to 'Add to network', new_network_path, class: "profile-sections" %>
          </div>        
        </div>
      </li>
      <li>
        <div class="w-row">
          <div class="w-col w-col-2">
            <%= link_to image_tag("edit.png"), edit_user_registration_path %>
          </div> 
          <div class="w-col w-col-10">
            <%= link_to 'Edit profile',edit_user_registration_path, class: "profile-sections" %>
          </div>        
        </div>
      </li>
    </ul>

  <% else %>
    
    <% if !current_user.nil? %>
    <ul class="w-list-unstyled">
      <li>
        <div class="w-row">
          <div class="w-col w-col-12">
            <h5>
              <% if current_user.friend_with? @user %>
                    <br>
                    You are friends
                    <br>
                    <%= link_to 'Remove', network_path(@user), :method => "delete", data: { confirm: 'Are you sure?' } %>
                  <% elsif current_user.invited? @user %>
                    <br>Pending request...
                  <% elsif @user.invited? current_user %>
                    <br> Waiting response
                    <br><%= link_to "Confirm", network_path(@user), :method => "put" %>
                    <br><%= link_to "Cancel", network_path(@user), :method => "delete" %>
                  <% else  %>
                    <br><%= link_to "Add", network_index_path(:user_id => @user), :method => "post" %>
              <% end %>
            </h5>
          </div>        
        </div>
      </li>
    </ul>
    <% end %>
  <% end %>

  <% if !@is_current_user and @current_user.admin? %>

     <ul class="w-list-unstyled">
      <li>
        <div class="w-row">
          <div class="w-col w-col-12">
            <h5>
              <%= link_to "Delete this user", admin_destroy_user_path(@user), method: :delete, data: { confirm: "You sure?" } %>
            </h5>
          </div>        
        </div>
      </li>
    </ul>

  <% end %>


</div>

muneris/app/views/layouts/partials/_suggestions.html.erb
<% if !@current_user.admin? %>

	<h1>Suggestions</h1>

	<ul class="w-list-unstyled feed">
		<% 	i = 0 
			suggested = [] %>
		<% 	for friend in current_user.friends
				for user in friend.friends
					if !user.friend_with? current_user and user != current_user and !suggested.include? user and !current_user.invited? user then 
					suggested << user %>
					<li>
						<div class="w-row">
							<div class="w-col w-col-3new">
								<%= link_to image_tag(user.avatar.url, class: "activity-image"), profile_path(user.id) %>
							</div>
							<div class="w-col w-col-9 w-small-6">    
								<%= link_to user.familyname, profile_path(user.id) %>
								<br><%= link_to "Add", network_index_path(:user_id => user), :method => "post" %>
							</div>
						</div>
					</li>
					<%	i +=1 
						break if i >= 10
					%>
				<% end %>
			<% end %>
		<% end %>
	</ul>

<% end %>