muneris/config/routes.rb
Muneris::Application.routes.draw do


  authenticated :user do
    root :to => "muneris#dashboard" , :as => "authenticated_root"
    # Rails 4 users must specify the 'as' option to give it a unique name
    # root :to => "main#dashboard", :as => "authenticated_root"
  end

  root :to => "welcome#index"

  resources :bills

  resources :network, :controller => 'friendships', :except => [:show, :edit] do
    get "requests", :on => :collection
    get "invites", :on => :collection
  end
  
  # get "/user/:id/feed", to: 'user#feed', as: :feed
  # get "/user/:id/notifications", to: 'user#notifications', as: :notifications
  # get "/user/:id/network", to: 'user#network', as: :usernetwork
  get "/dashboard", to: 'muneris#dashboard', as: :dashboard
  get "/profile(/:user_id)", to: 'muneris#profile', as: :profile
  get "/statistics", to: 'muneris#statistics', as: :statistics
  get "/map", to: 'muneris#map', as: :map
  get "/map/info/:user_map_id", to: 'muneris#map'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  delete 'profile/:id' => 'user#destroy', :as => :admin_destroy_user  

end

muneris/app/models/bill.rb
class Bill < ActiveRecord::Base
	include PublicActivity::Common
  	# tracked owner: ->(controller, model) { controller && controller.current_user }
  	
	has_many :userbills , :dependent => :destroy
 	has_many :users, :through => :userbills

 	def to_s
 		"(#{id})"
 	end

end

muneris/app/controllers/bills_controller.rb
class BillsController < ApplicationController
  include ActionView::Helpers::NumberHelper

  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills_grid = initialize_grid(
      current_user.bills,
      order:           'bills.date',
      order_direction: 'desc',
      per_page: 12
    )

    bills = current_user.bills.sort_by(&:date)

    @ebills, @wbills, @gbills = [], [], []

    bills.each do |b|
      case b.service
      when 1
        @ebills << [b.date.strftime("%s%L").to_i,b.consumption]
      when 2
        @wbills << [b.date.strftime("%s%L").to_i,b.consumption]
      when 3
        @gbills << [b.date.strftime("%s%L").to_i,b.consumption]
      end
    end

    @echart = LazyHighCharts::HighChart.new('graph') do |f|
      f.chart(style: {width: '100%'})
      f.yAxis({:title => {:text => "Consumption", :margin => 20} })
      f.series(name: "Energy bills", :yAxis => 0, :data => @ebills, tooltip: {valueSuffix: ' kWh'})
      f.rangeSelector(enabled: true, inputDateFormat: '%b %Y', inputEditDateFormat: '%b %Y')    
    end
    @wchart = LazyHighCharts::HighChart.new('graph') do |f|
      f.chart(style: {width: '100%'})
      f.yAxis({:title => {:text => "Consumption", :margin => 20} })
      f.series(name: "Water bills", :yAxis => 0, :data => @wbills, tooltip: {valueSuffix: ' m3'})
      f.rangeSelector(enabled: true, inputDateFormat: '%b %Y', inputEditDateFormat: '%b %Y')    
    end
    @gchart = LazyHighCharts::HighChart.new('graph') do |f|
      f.chart(style: {width: '100%'})
      f.yAxis({:title => {:text => "Consumption", :margin => 20} })
      f.series(name: "Gas bills", :yAxis => 0, :data => @gbills, tooltip: {valueSuffix: ' m3'})
      f.rangeSelector(enabled: true, inputDateFormat: '%b %Y', inputEditDateFormat: '%b %Y')    
    end

  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        current_user.userbills.create!(bill_id: @bill.id)

        @bill.create_activity :create, owner: current_user, parameters: Hash["consumption" => consumption, "value" => value, "time" => time]
      
        alerts
              
        format.html { redirect_to profile_path, notice: 'Bill was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bill }
      else
        format.html { render action: 'new' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        @bill.create_activity :update, owner: current_user, parameters: Hash["consumption" => consumption, "value" => value, "time" => time]
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    # @bill.create_activity :destroy, owner: current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:consumption, :value, :service, :date)
    end

    def alerts

      avg_bill_yours = current_user.bills.where(:service => @bill.service).average(:consumption)

      avg_bill_tariff = Bill.joins("INNER JOIN userbills ON userbills.bill_id = bills.id INNER JOIN users ON userbills.user_id = users.id INNER JOIN friendships ON (users.id = friendships.friendable_id OR users.id = friendships.friend_id)").where('bills.service = ? AND users.id not IN (?) AND (friendships.friendable_id= ? OR friendships.friend_id = ?) AND friendships.pending = 0 AND friendships.blocker_id IS NULL AND users.tariff = ?', @bill.service, current_user.id, current_user.id, current_user.id, current_user.tariff).average("consumption").to_f

      avg_bill_neighbors = Bill.joins("INNER JOIN userbills ON userbills.bill_id = bills.id INNER JOIN users ON userbills.user_id = users.id INNER JOIN friendships ON (users.id = friendships.friendable_id OR users.id = friendships.friend_id)").where('bills.service = ? AND users.id not IN (?) AND (friendships.friendable_id= ? OR friendships.friend_id = ?) AND friendships.pending = 0 AND friendships.blocker_id IS NULL AND users.address = ?', @bill.service, current_user.id, current_user.id, current_user.id, current_user.address).average("consumption").to_f

      if @bill.consumption > 1.8*avg_bill_tariff     and !avg_bill_tariff.zero?
        create_alert
      elsif @bill.consumption > 1.65*avg_bill_neighbors and !avg_bill_neighbors.zero?
       create_alert
      elsif @bill.consumption > 1.5*avg_bill_yours      and current_user.bills.where(:service => @bill.service).count > 1
        create_alert
      end

    end

    def create_alert
      PublicActivity::Activity.create!({
            :trackable_id =>@bill.id,
            :trackable_type => "Bill",
            :owner_id => current_user.id,
            :owner_type => "User",
            :key => "bill.alert",
            :parameters => Hash["consumption" => consumption, "value" => value, "time" => time]
            })
    end

    def consumption
      case @bill.service
      when 1
        @bill.consumption.to_s + " kWh"
      else 
        @bill.consumption.to_s + " m3"
      end
    end

    def value
      number_to_currency(@bill.value.to_i, :precision => 0)
    end

    def time
      @bill.date.strftime("%b %Y")
    end
end

muneris/app/helpers/bills_helper.rb
module BillsHelper
end

muneris/app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="pre-sign-up">
    <div class="w-form">
    	<div class="field">
			<%= f.label :service, "Type of bill service" %>
			<%= select_tag("bill[service]", options_for_select([
																["Energy Bill",1],
			                                                    ["Water Bill",2],
			                                                    ["Gas Bill",3]
		                                          		    	]), class: 'w-input', prompt: "Select an option") %>
		</div>
		<div class="field">
			<%= f.label :consumption, id: 'consum' %>
			<%= f.number_field :consumption, class: "w-input", :step => 'any'%>
		</div>
		<div class="field">
			<%= f.label :value, "Payment ($)" %>
			<%= f.number_field :value, class: "w-input" %>
		</div>
		<div class="field">
			<%= f.label :date %>
			<%= f.date_select :date, class: "w-input", discard_day: 'true'%>
		</div>
	</div>
	<br><br>
  	<div class="actions w-container external-buttons" style="width:100%; position: relative">
		<%= f.submit "Save bill", class: "w-button clickable" %>
	</div>
  </div>
  
	

<% end %>

<script type="text/javascript">
  var newLabel = 'Consumption';
  $('#bill_service').on('change', function(){
      switch(this.value){
          case '1':
              newLabel = 'Consumption (kWh)';
              break;
          case '2':
              newLabel = 'Consumption (m3)';
              break;
          case '3':
              newLabel = 'Consumption (m3)';
              break;
      }
      $('#consum').text(newLabel);
  }).trigger('change');
</script>

muneris/app/views/bills/_grid.html.erb
<% define_grid(@bills_grid, hide_submit_button: true, hide_reset_button: true) do |g|

  g.blank_slate  partial: 'layouts/partials/blank', locals: { section: 'bill' }

  g.column name: 'Consumption', attribute: 'consumption', auto_reload:  true, detach_with_id: :consumption_filter do |bill|
    case bill.service
    when 1
      bill.consumption.to_s + " kWh"
    when 2
      bill.consumption.to_s + " m3"
    when 3
      bill.consumption.to_s + " m3"
    end
  end

  g.column  name: 'Payment', attribute: 'value', auto_reload:  true, detach_with_id: :value_filter do |bill|
    number_to_currency(bill.value, :precision => 0)
  end

  g.column name: 'Date', attribute: 'date', auto_reload: true, detach_with_id: :date_added, helper_style: :standard do |bill|
    bill.date.strftime "%b %Y"
  end

  g.column name: 'Type of bill', attribute: 'service', auto_reload: true, detach_with_id: :service_filter, custom_filter: [['Energy Bill',1],['Water Bill',2],['Gas Bill',3]] do |bill|
    case bill.service
    when 1
      "Energy"
    when 2
      "Water"
    when 3
      "Gas"
    end
  end

  g.column do |bill|
    link_to 'Show', bill
  end

  g.column do |bill|
    link_to'Edit', edit_bill_path(bill)
  end

  g.column do |bill|
    link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' }
  end

end %>

muneris/app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', :back %>

muneris/app/views/bills/index.html.erb
<h1>Bills</h1>

<% render partial: 'grid' %>

<div class="w-container">
  <div class="w-row">
    <div class="w-col w-col-2">
        <div class="w-row">
          <div class="w-col w-col-2">
            <%= link_to image_tag("add.png"), new_bill_path %>
          </div>
          <div class="w-col w-col-10">
            <h4><%= link_to 'Add new', new_bill_path, class: "profile-sections" %></h4>
          </div>        
        </div>
    </div>
  </div>
  <div class="w-row">
    <div class="w-col w-col-2">
      <div class ="wg-detached-filter">
        <div>Consumption: <%= grid_filter @bills_grid, :consumption_filter %></div>
        
        <div>Payment:  <%= grid_filter @bills_grid, :value_filter %></div>

        <div>Type of bill:  <%= grid_filter @bills_grid, :service_filter %></div>

        <div>Date:	<%= grid_filter @bills_grid, :date_added %></div>
      </div>
      <div class="external-buttons">
        <button class="btn btn-primary wg-external-submit-button" data-grid-name="grid">Filter grid</button>
        <button class="btn wg-external-reset-button" data-grid-name="grid">Reset grid</button>
      </div>
    </div>
    <div class="w-col w-col-10">
      <div class="wice-grid">
        <%= render_grid(@bills_grid) %>
      </div>
    </div>
  </div>
  <div class="w-row">
  <div id="radio_buttons">
        <form class="type flash">
            <input type="radio" name="type" checked="checked" value="1">Energy bills</input>
            <input type="radio" name="type" value="2">Water bills</input>
            <input type="radio" name="type" value="3">Gas bills</input>
        </form>
    </div>  
    <div class="w-col w-col-11">
      <%= high_stock("echart", @echart) %>
      <%= high_stock("wchart", @wchart) %>
      <%= high_stock("gchart", @gchart) %>
      <div class="asterisk">*This chart is independent from the above filters.</div>
    </div>
  </div>
</div>


<script>
    $( document ).ready(function() {

      $('#echart').show();
      $('#wchart').hide();
      $('#gchart').hide();

    $("#radio_buttons input[name='type']").click(function(){
        if($('input:radio[name=type]:checked').val() == "1"){
          $('#echart').show();
          $('#wchart').hide();
          $('#gchart').hide();
        }
        if($('input:radio[name=type]:checked').val() == "2"){
          $('#echart').hide();
          $('#wchart').show();
          $('#gchart').hide();
        }
        if($('input:radio[name=type]:checked').val() == "3"){
          $('#echart').hide();
          $('#wchart').hide();
          $('#gchart').show();
        }

    });
    });


</script>

muneris/app/views/bills/new.html.erb
<div>
	<div class="hero-bg">
		<div class="w-container container-1">
			<h1 class="log-title" id="page-nav-Section-1">Add new bill</h1>
			<%= render 'form' %>
			<p>
				<%= link_to 'Back', :back %>
			</p>
		</div>
	</div>
</div>

muneris/app/views/bills/show.html.erb
<div class="w-container container-1">
	<p>
	  <strong>Consumption:</strong>
	  <%= case @bill.service
    when 1
      @bill.consumption.to_s + " kWh"
    when 2
      @bill.consumption.to_s + " m3"
    when 3
      @bill.consumption.to_s + " m3"
    end %>
	</p>

	<p>
	  <strong>Value:</strong>
	  <%= number_to_currency(@bill.value, :precision => 0) %>
	</p>

	<p>
	  <strong>Date:</strong>
	  <%= @bill.date.strftime "%b %Y" %>
	</p>
	<p>
	  <%= link_to 'Edit', edit_bill_path(@bill) %>
	  |
	  <%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %>
	  1
	  <%= link_to 'Back', bills_path %>
	</p>
</div>